# Generated by Django 5.2.7 on 2025-10-22 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('nombre_jeux_donnees', models.IntegerField(default=0, verbose_name='Nombre de jeux de données')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('nom_complet', models.CharField(blank=True, max_length=500, verbose_name='Nom complet')),
                ('type_organisation', models.CharField(max_length=100, verbose_name="Type d'organisation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('nombre_jeux_donnees', models.IntegerField(default=0, verbose_name='Nombre de jeux de données')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='JeuDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('categories', models.CharField(max_length=500, verbose_name='Catégories')),
                ('etiquettes', models.CharField(blank=True, max_length=500, verbose_name='Étiquettes')),
                ('niveau_acces', models.CharField(default='Ouvert', max_length=50, verbose_name="Niveau d'accès")),
                ('url_originale', models.URLField(blank=True, verbose_name='URL originale')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_metadata_creation', models.DateTimeField(blank=True, null=True, verbose_name='Date de création des métadonnées')),
                ('date_metadata_modification', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification des métadonnées')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Jeu de données',
                'verbose_name_plural': 'Jeux de données',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, verbose_name='Nom')),
                ('format_fichier', models.CharField(max_length=50, verbose_name='Format du fichier')),
                ('type_ressource', models.CharField(max_length=100, verbose_name='Type de ressource')),
                ('url', models.URLField(verbose_name='URL')),
                ('taille', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (bytes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('methode_collecte', models.TextField(blank=True, verbose_name='Méthode de collecte')),
                ('contexte_collecte', models.TextField(blank=True, verbose_name='Contexte de collecte')),
                ('attributs', models.TextField(blank=True, verbose_name='Attributs')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('jeu_donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.jeudonnees', verbose_name='Jeu de données')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['nom'],
            },
        ),
    ]
