# Generated by Django 5.2.7 on 2025-11-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFiltres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la configuration')),
                ('actif', models.BooleanField(default=True, verbose_name='Configuration active')),
                ('organisations_filtres', models.TextField(blank=True, verbose_name='Organisations à inclure (séparées par ;)')),
                ('categories_filtres', models.TextField(blank=True, verbose_name='Catégories à inclure (séparées par ;)')),
                ('formats_fichiers', models.CharField(blank=True, max_length=200, verbose_name='Formats de fichiers (séparés par ;)')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début (jeux créés après)')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin (jeux créés avant)')),
                ('niveau_acces', models.CharField(blank=True, max_length=50, verbose_name="Niveau d'accès (Ouvert/Privé)")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Configuration de filtres',
                'verbose_name_plural': 'Configurations de filtres',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SourceDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la source')),
                ('url_base', models.URLField(verbose_name="URL de base de l'API")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Source active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('derniere_synchronisation', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
            ],
            options={
                'verbose_name': 'Source de données',
                'verbose_name_plural': 'Sources de données',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la planification')),
                ('active', models.BooleanField(default=False, verbose_name='Planification active')),
                ('frequence', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('personnalise', 'Personnalisé')], default='quotidien', max_length=20, verbose_name='Fréquence')),
                ('heure_execution', models.TimeField(default='03:00', verbose_name="Heure d'exécution")),
                ('jour_semaine', models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], null=True, verbose_name='Jour de la semaine')),
                ('jour_mois', models.IntegerField(blank=True, null=True, verbose_name='Jour du mois (1-31)')),
                ('expression_cron', models.CharField(blank=True, help_text='Format: minute heure jour mois jour_semaine', max_length=100, verbose_name='Expression cron (ex: 0 3 * * *)')),
                ('prochaine_execution', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine exécution prévue')),
                ('derniere_execution', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('configuration_filtres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donnees.configurationfiltres', verbose_name='Configuration de filtres à appliquer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.sourcedonnees', verbose_name='Source de données')),
            ],
            options={
                'verbose_name': 'Configuration de planification',
                'verbose_name_plural': 'Configurations de planification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='configurationfiltres',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donnees.sourcedonnees', verbose_name='Source de données'),
        ),
    ]
